### ISSUE TITLE
Commit 6ed3e71 breaks application on Linux

### ISSUE THREAD

**Issue by HurricanePootis** [mmvanheusden/SteamDepotDownloaderGUI#262]
**Describe the bug**  
A clear and concise description of the bug.

Building the 3.0.1 tag for linux resulted in the application breaking. After bisecting the commits, I discovered https://github.com/mmvanheusden/SteamDepotDownloaderGUI/commit/6ed3e7153657b0c2b791d438bf8dc4627042606e to be the cause of the issue

Whenever launching the program, I get the following error:
```
thread 'tokio-runtime-worker' panicked at src/main.rs:44:68:
called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }
```

Whenever running with `RUST_BACKTRACE=full`, I get the following information:
```
thread 'tokio-runtime-worker' panicked at src/main.rs:44:68:
called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }
stack backtrace:
   0:     0x635ae4c8052a - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::h5b6bd5631a6d1f6b
   1:     0x635ae4cacac3 - core::fmt::write::h7550c97b06c86515
   2:     0x635ae4c7c4e3 - std::io::Write::write_fmt::h7b09c64fe0be9c84
   3:     0x635ae4c80372 - std::sys::backtrace::BacktraceLock::print::h2395ccd2c84ba3aa
   4:     0x635ae4c8167c - std::panicking::default_hook::{{closure}}::he19d4c7230e07961
   5:     0x635ae4c814c2 - std::panicking::default_hook::hf614597d3c67bbdb
   6:     0x635ae4c81c57 - std::panicking::rust_panic_with_hook::h8942133a8b252070
   7:     0x635ae4c81aea - std::panicking::begin_panic_handler::{{closure}}::hb5f5963570096b29
   8:     0x635ae4c80a09 - std::sys::backtrace::__rust_end_short_backtrace::h6208cedc1922feda
   9:     0x635ae4c8177c - rust_begin_unwind
  10:     0x635ae4432780 - core::panicking::panic_fmt::h0c3082644d1bf418
  11:     0x635ae4432bc6 - core::result::unwrap_failed::hd20b4aa073bda1e2
  12:     0x635ae45c8a7f - <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll::h3f0c5233872c0244
  13:     0x635ae44d2c45 - tauri::ipc::InvokeResolver<R>::respond_async_serialized::{{closure}}::h761d6dd7da9bed38
  14:     0x635ae45113fb - tokio::runtime::task::core::Core<T,S>::poll::h477bc2f1a2abd455
  15:     0x635ae446add9 - tokio::runtime::task::harness::Harness<T,S>::poll::h876ae07fa93f125b
  16:     0x635ae4af52c7 - tokio::runtime::scheduler::multi_thread::worker::Context::run_task::h62a214b28412ff16
  17:     0x635ae4af3bd9 - tokio::runtime::scheduler::multi_thread::worker::Context::run::h1e21de083aeaa7f7
  18:     0x635ae4afa598 - tokio::runtime::context::scoped::Scoped<T>::set::h14a84b6b9635df44
  19:     0x635ae4b05684 - tokio::runtime::context::runtime::enter_runtime::hc28dcd72d7c690f8
  20:     0x635ae4af39b1 - tokio::runtime::scheduler::multi_thread::worker::run::h010d436b298889fd
  21:     0x635ae4b08288 - tokio::runtime::task::core::Core<T,S>::poll::hae3d494a24a8ae92
  22:     0x635ae4af0e1d - tokio::runtime::task::harness::Harness<T,S>::poll::hc24f3eca13e31ed8
  23:     0x635ae4b02adf - tokio::runtime::blocking::pool::Inner::run::ha45df24acdf2eb76
  24:     0x635ae4afb0e1 - std::sys::backtrace::__rust_begin_short_backtrace::h584fad613e8f3841
  25:     0x635ae4afb92b - core::ops::function::FnOnce::call_once{{vtable.shim}}::hd4a9acf821d605bb
  26:     0x635ae4c884db - std::sys::pal::unix::thread::Thread::new::thread_start::hcc78f3943333fa94
  27:     0x7546f8c6439d - <unknown>
  28:     0x7546f8ce949c - <unknown>
  29:                0x0 - <unknown>
```

**Describe the solution you'd like**  
<A clear and concise description of what you want to happen.>

For the reason as to why the application is breaking to be fixed

**Additional context**  
Add any other context or screenshots about the bug report here.

Building with pnpm 9.15.0 and rust 1.83.0

**Comment by mmvanheusden** [comment]
Hm, seems to be an issue with forcing the working directory to a location chosen by Tauri (`app.path().app_cache_dir()`). However doesn't happen on my PC but i'll see if i can implement this better.

> For the reason as to why the application is breaking to be fixed

This isn't the reason Linux is broken. The reason Linux builds are broken is because for some reason the system shell completely breaks when the app is packaged as a bundle (AppImage). I believe this is a Tauri issue and should be fixed on Tauri's end.

**Comment by HurricanePootis** [comment]
I am not building it as an appimage. I am running the binary directly.
